"""add normalized_value to findings (fix)

Revision ID: a119b6af3179
Revises: 4dbaf8718c46
Create Date: 2026-09-22 11:17:54.380770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a119b6af3179'
down_revision: Union[str, Sequence[str], None] = '4dbaf8718c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('normalized_value', sa.String(), nullable=True))
    op.create_index('ix_findings_dedup', 'findings', ['target_id', 'type', 'normalized_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_findings_dedup', table_name='findings')
    op.drop_column('findings', 'normalized_value')
    # ### end Alembic commands ###
