SHERLOCK_CATEGORIES = {
    "Social Media": [
        "9GAG", "Bluesky", "Chaos", "Clapper", "Clubhouse", "Discord.bio",
        "Fosstodon", "Framapiaf", "Giphy", "Ifunny", "Imgur", "Instagram",
        "Mamot", "Myspace", "Pinterest", "Plurk", "Pronouns.page", "Reddit",
        "ShitpostBot5000", "Snapchat", "SpaceHey", "Status Cafe",
        "Tellonym.me", "Tenor", "TikTok", "Twitter", "Untappd", "VK",
        "Vero", "Wykop", "chaos.social", "d3RU", "datingRU", "dcinside",
        "imood", "interpals", "jbzd.com.pl", "mastodon.cloud",
        "mastodon.social", "mastodon.xyz", "minds", "mstdn.io",
        "mstdn.social", "nairaland.com", "pikabu", "pixelfed.social",
        "pr0gramm", "social.tchncs.de", "threads", "tumblr",
    ],
    "Developer": [
        "Apple Developer", "Asciinema", "Atcoder", "BitBucket", "BugCrowd",
        "CSSBattle", "CTAN", "Cplusplus", "Code Snippet Wiki", "Codeberg",
        "CodeSandbox", "Codechef", "Codeforces", "Codepen", "Coders Rank",
        "Coderwall", "Codewars", "Codolio", "Crowdin", "CyberDefenders",
        "DEV Community", "DMOJ", "Discuss.Elastic.co", "Docker Hub",
        "GNOME VCS", "GeeksforGeeks", "GitBook", "GitHub", "GitLab",
        "Gitea", "Gitee", "Gradle", "HackMD", "HackTheBox", "Hackaday",
        "HackenProof (Hackers)", "HackerEarth", "HackerNews", "HackerOne",
        "HackerRank", "HackerSploit", "Hashnode", "Holopin", "HudsonRock",
        "Hugging Face", "Intigriti", "Ionic Forum", "Jellyfin Weblate",
        "Jupyter Community Forum", "Kaggle", "Laracast", "Launchpad",
        "LeetCode", "LinuxFR.org", "Lobsters", "NICommunityForum", "Needrom",
        "Nextcloud Forum", "NotABug.org", "ObservableHQ", "Open Collective",
        "OpenGameArt", "Opensource", "Packagist", "Pastebin", "PentesterLab",
        "PyPi", "Python.org Discussions", "Rclone Forum", "Replit.com",
        "Ruby Forums", "RubyGems", "SourceForge", "SublimeForum", "Topcoder",
        "TryHackMe", "VirusTotal", "Vjudge", "WICG Forum", "Wakatime",
        "Weblate", "WordPressOrg", "devRant", "freecodecamp", "habr",
        "hackster", "n8n Community", "npm", "opennet", "phpRU", "prog.hu",
        "programming.dev",
    ],
    "Creative": [
        "2Dimensions", "Anilist", "Archive of Our Own", "ArtStation",
        "Behance", "Blipfoto", "Carbonmade", "ColourLovers", "Crevado",
        "Cults3D", "DeviantArt", "Dribbble", "Exposure", "EyeEm", "Flickr",
        "Houzz", "Icons8 Community", "ImgUp.cz", "Instructables",
        "Letterboxd", "LottieFiles", "MyAnimeList", "MyMiniFactory",
        "Mydramalist", "Rajce.net", "Sketchfab", "SmugMug", "TheMovieDB",
        "Trakt", "Unsplash", "VSCO", "Wattpad", "YouPic", "fl",
        "furaffinity",
    ],
    "Gaming": [
        "Blitz Tactics", "BoardGameGeek", "Cfx.re Forum", "Chess",
        "CurseForge", "Fandom", "Fanpop", "FortniteTracker", "GameFAQs",
        "Gamespot", "Giant Bomb", "Itch.io", "Kongregate", "Lichess",
        "MMORPG Forum", "Minecraft", "NationStates Nation",
        "NationStates Region", "Newgrounds", "Nightbot", "Ninja Kiwi",
        "NintendoLife", "NitroType", "Outgress", "PCGamer",
        "PSNProfiles.com", "Patched", "Playstrategy", "Pokemon Showdown",
        "Polygon", "Polymart", "Pychess", "Realmeye", "Roblox", "RuneScape",
        "Splits.io", "Speedrun.com", "Sporcle", "Star Citizen",
        "Steam Community (Group)", "Steam Community (User)", "TETR.IO",
        "Terraria Forums", "Typeracer", "Valorant Forums", "Warframe Market",
        "Wowhead", "Xbox Gamertag", "addons.wago.io", "exophase",
        "igromania", "jeuxvideo", "osu!", "TrashboxRU",
    ],
    "Music": [
        "Airbit", "Audiojungle", "Bandcamp", "Discogs", "Freesound",
        "Genius (Artists)", "Genius (Users)", "MixCloud", "MuseScore",
        "PromoDJ", "Rate Your Music", "ReverbNation", "Smule", "SoundCloud",
        "Splice", "Spotify", "TRAKTRAIN", "Tuna", "Ultimate-Guitar",
        "YandexMusic", "last.fm",
    ],
    "Professional": [
        "About.me", "AllMyLinks", "BuyMeACoffee", "Carrd", "Contently",
        "Coroflot", "Freelancer", "Gravatar", "Jimdo", "LinkedIn",
        "Linktree", "Patreon", "ProductHunt", "Slides", "SpeakerDeck",
        "Topmate", "Trello", "Warrior Forum", "WebNode", "Weebly", "Wix",
        "authorSTREAM", "kofi", "kwork", "moikrug", "sessionize",
    ],
    "Forum / Community": [
        "7Cups", "Apple Discussions", "Arduino Forum", "Ask Fedora",
        "Autofrage", "BabyRu", "BioHacking", "Bitwarden Forum",
        "Bookcrossing", "BraveCommunity", "BreachSta.rs Forum",
        "Caddy Community", "Car Talk Community", "Choice Community",
        "CloudflareCommunity", "Cracked Forum", "Cryptomator Forum",
        "DigitalSpy", "Diskusjon.no", "Disqus", "Eintracht Frankfurt Forum",
        "Envato Forum", "Finanzfrage", "GaiaOnline", "Gesundheitsfrage",
        "Gutefrage", "Hubski", "IRC-Galleria", "Joplin Forum",
        "Kvinneguiden", "LOR", "LemmyWorld", "LessWrong", "Motorradfrage",
        "Nothing Community", "OurDJTalk", "SEOForum", "SoylentNews", "Slant",
        "Slashdot", "Spells8", "Tweakers", "VLR", "Velomania", "Wikidot",
        "WolframalphaForum", "babyblogRU", "drive2", "eGPU", "eintracht",
        "fixya", "forum_guns", "hunting", "kaskus", "namuwiki", "nnRU",
        "satsisRU", "spletnik", "toster", "znanylekarz.pl",
    ],
    "Crypto / Web3": [
        "Coinvote", "CryptoHack", "Hive Blog", "Rarible",
    ],
    "NSFW": [
        "1337x", "APClips", "AdmireMe.Vip", "All Things Worn", "Avizo",
        "BongaCams", "ChaturBate", "Erome", "Forum Ophilia", "Heavy-R",
        "Image Fap", "LushStories", "Motherless", "PocketStars", "Pornhub",
        "RedTube", "RocketTube", "RoyalCams", "TnAFlix", "Xvideos",
        "YouPorn", "xHamster",
    ],
    "Video / Streaming": [
        "Aparat", "AniWorld", "DailyMotion", "Itemfix", "Kick", "Nyaa.si",
        "Odysee", "Periscope", "Rumble", "SOOP", "Trovo", "Twitch",
        "Vimeo", "YouNow", "YouTube", "svidbook",
    ],
    "Blog / Media": [
        "Archive.org", "Blogger", "BuzzFeed", "CNET", "Cracked", "Flipboard",
        "GoodReads", "HubPages", "Instapaper", "Issuu", "LibraryThing",
        "Listed", "LiveJournal", "Medium", "Naver", "Scribd", "Shelf",
        "SlideShare", "Substack", "Velog", "WordPress", "akniga", "dailykos",
        "livelib", "note", "tistory", "write.as",
    ],
    "Shopping / Marketplace": [
        "BOOTH", "Bazar.cz", "CGTrader", "Chollometro", "Dealabs",
        "Empretienda AR", "Fameswap", "Google Play", "Grailed", "Gumroad",
        "HotUKdeals", "Mydealz", "PepperNL", "PepperPL", "Pepperdeals",
        "PepperealsUS", "PlayStore", "Preisjaeger", "Promodescuentos",
        "Redbubble", "SWAPD", "Sbazar.cz", "ThemeForest", "Tiendanube",
        "irecommend", "mercadolivre",
    ],
    "Messaging": [
        "Chatujme.cz", "Discord", "Keybase", "Kik", "Signal", "Slack",
        "Telegram",
    ],
    "Education": [
        "Academia.edu", "Codecademy", "Clozemaster", "Credly", "Duolingo",
        "GetMyUni", "Harvard Scholar", "Memrise", "Platzi", "ResearchGate",
        "Scratch", "Wikipedia", "Wordnik",
    ],
    "Finance": [
        "BiggerPockets", "CashApp", "TradingView", "Venmo", "leasehackr",
    ],
    "Sport / Fitness": [
        "Championat", "F3.cool", "Football", "Pinkbike", "Sportlerfrage",
        "SportsRU", "Strava",
    ],
    "Travel": [
        "Airliners", "Flightradar24", "Polarsteps", "Reisefrage",
        "Trawelling", "couchsurfing", "geocaching",
    ],
    "Other": [
        "Bezuzyteczna", "Career.habr", "IFTTT", "Monkeytype",
        "OpenStreetMap", "Windy", "omg.lol", "uid",
    ],
}
