SHERLOCK_SITES = {
    "1337x", "2Dimensions", "7Cups", "9GAG", "APClips", "AWS Skills Profile",
    "About.me", "Academia.edu", "AdmireMe.Vip", "Airbit", "Airliners", "All Things Worn",
    "AllMyLinks", "AniWorld", "Anilist", "Aparat", "Apple Developer", "Apple Discussions",
    "Archive of Our Own", "Archive.org", "Arduino Forum", "ArtStation", "Asciinema", "Ask Fedora",
    "Atcoder", "Audiojungle", "Autofrage", "Avizo", "BOOTH", "BabyRu",
    "Bandcamp", "Bazar.cz", "Behance", "Bezuzyteczna", "BiggerPockets", "BioHacking",
    "BitBucket", "Bitwarden Forum", "Blipfoto", "Blitz Tactics", "Blogger", "Bluesky",
    "BoardGameGeek", "BongaCams", "Bookcrossing", "BraveCommunity", "BreachSta.rs Forum", "BugCrowd",
    "BuyMeACoffee", "BuzzFeed", "CGTrader", "CNET", "CSSBattle", "CTAN",
    "Caddy Community", "Car Talk Community", "Carbonmade", "Career.habr", "Carrd", "CashApp",
    "Cfx.re Forum", "Championat", "Chaos", "Chatujme.cz", "ChaturBate", "Chess",
    "Choice Community", "Chollometro", "Clapper", "CloudflareCommunity", "Clozemaster", "Clubhouse",
    "Code Snippet Wiki", "CodeSandbox", "Codeberg", "Codecademy", "Codechef", "Codeforces",
    "Codepen", "Coders Rank", "Coderwall", "Codewars", "Codolio", "Coinvote",
    "ColourLovers", "Contently", "Coroflot", "Cplusplus", "Cracked", "Cracked Forum",
    "Credly", "Crevado", "Crowdin", "CryptoHack", "Cryptomator Forum", "Cults3D",
    "CurseForge", "CyberDefenders", "DEV Community", "DMOJ", "DailyMotion", "Dealabs",
    "DeviantArt", "DigitalSpy", "Discogs", "Discord", "Discord.bio", "Discuss.Elastic.co",
    "Diskusjon.no", "Disqus", "Docker Hub", "Dribbble", "Duolingo", "Eintracht Frankfurt Forum",
    "Empretienda AR", "Envato Forum", "Erome", "Exposure", "EyeEm", "F3.cool",
    "Fameswap", "Fandom", "Fanpop", "Finanzfrage", "Flickr", "Flightradar24",
    "Flipboard", "Football", "FortniteTracker", "Forum Ophilia", "Fosstodon", "Framapiaf",
    "Freelancer", "Freesound", "GNOME VCS", "GaiaOnline", "GameFAQs", "Gamespot",
    "GeeksforGeeks", "Genius (Artists)", "Genius (Users)", "Gesundheitsfrage", "GetMyUni", "Giant Bomb",
    "Giphy", "GitBook", "GitHub", "GitLab", "Gitea", "Gitee",
    "GoodReads", "Google Play", "Gradle", "Grailed", "Gravatar", "Gumroad",
    "Gutefrage", "HackMD", "HackTheBox", "Hackaday", "HackenProof (Hackers)", "HackerEarth",
    "HackerNews", "HackerOne", "HackerRank", "HackerSploit", "Harvard Scholar", "Hashnode",
    "Heavy-R", "Hive Blog", "Holopin", "HotUKdeals", "Houzz", "HubPages",
    "Hubski", "HudsonRock", "Hugging Face", "IFTTT", "IRC-Galleria", "Icons8 Community",
    "Ifunny", "Image Fap", "ImgUp.cz", "Imgur", "Instagram", "Instapaper",
    "Instructables", "Intigriti", "Ionic Forum", "Issuu", "Itch.io", "Itemfix",
    "Jellyfin Weblate", "Jimdo", "Joplin Forum", "Jupyter Community Forum", "Kaggle", "Keybase",
    "Kick", "Kik", "Kongregate", "Kvinneguiden", "LOR", "Laracast",
    "Launchpad", "LeetCode", "LemmyWorld", "LessWrong", "Letterboxd", "LibraryThing",
    "Lichess", "LinkedIn", "Linktree", "LinuxFR.org", "Listed", "LiveJournal",
    "Lobsters", "LottieFiles", "LushStories", "MMORPG Forum", "Mamot", "Medium",
    "Memrise", "Minecraft", "MixCloud", "Monkeytype", "Motherless", "Motorradfrage",
    "MuseScore", "MyAnimeList", "MyMiniFactory", "Mydealz", "Mydramalist", "Myspace",
    "NICommunityForum", "NationStates Nation", "NationStates Region", "Naver", "Needrom", "Newgrounds",
    "Nextcloud Forum", "Nightbot", "Ninja Kiwi", "NintendoLife", "NitroType", "NotABug.org",
    "Nothing Community", "Nyaa.si", "ObservableHQ", "Odysee", "Open Collective", "OpenGameArt",
    "OpenStreetMap", "Opensource", "OurDJTalk", "Outgress", "PCGamer", "PSNProfiles.com",
    "Packagist", "Pastebin", "Patched", "Patreon", "PentesterLab", "PepperNL",
    "PepperPL", "Pepperdeals", "PepperealsUS", "Periscope", "Pinkbike", "Pinterest",
    "Platzi", "PlayStore", "Playstrategy", "Plurk", "PocketStars", "Pokemon Showdown",
    "Polarsteps", "Polygon", "Polymart", "Pornhub", "Preisjaeger", "ProductHunt",
    "PromoDJ", "Promodescuentos", "Pronouns.page", "PyPi", "Pychess", "Python.org Discussions",
    "Rajce.net", "Rarible", "Rate Your Music", "Rclone Forum", "Realmeye", "RedTube",
    "Redbubble", "Reddit", "Reisefrage", "Replit.com", "ResearchGate", "ReverbNation",
    "Roblox", "RocketTube", "RoyalCams", "Ruby Forums", "RubyGems", "Rumble",
    "RuneScape", "SEOForum", "SOOP", "SWAPD", "Sbazar.cz", "Scratch",
    "Scribd", "Shelf", "ShitpostBot5000", "Signal", "Sketchfab", "Slack",
    "Slant", "Slashdot", "SlideShare", "Slides", "SmugMug", "Smule",
    "Snapchat", "SoundCloud", "SourceForge", "SoylentNews", "SpaceHey", "SpeakerDeck",
    "Speedrun.com", "Spells8", "Splice", "Splits.io", "Sporcle", "Sportlerfrage",
    "SportsRU", "Spotify", "Star Citizen", "Status Cafe", "Steam Community (Group)", "Steam Community (User)",
    "Strava", "SublimeForum", "Substack", "TETR.IO", "TRAKTRAIN", "Telegram",
    "Tellonym.me", "Tenor", "Terraria Forums", "TheMovieDB", "ThemeForest", "Tiendanube",
    "TikTok", "TnAFlix", "Topcoder", "Topmate", "TradingView", "Trakt",
    "TrashboxRU", "Trawelling", "Trello", "Trovo", "TryHackMe", "Tuna",
    "Tweakers", "Twitch", "Twitter", "Typeracer", "Ultimate-Guitar", "Unsplash",
    "Untappd", "VK", "VLR", "VSCO", "Valorant Forums", "Velog",
    "Velomania", "Venmo", "Vero", "Vimeo", "VirusTotal", "Vjudge",
    "WICG Forum", "Wakatime", "Warframe Market", "Warrior Forum", "Wattpad", "WebNode",
    "Weblate", "Weebly", "Wikidot", "Wikipedia", "Windy", "Wix",
    "WolframalphaForum", "WordPress", "WordPressOrg", "Wordnik", "Wowhead", "Wykop",
    "Xbox Gamertag", "Xvideos", "YandexMusic", "YouNow", "YouPic", "YouPorn",
    "YouTube", "addons.wago.io", "akniga", "authorSTREAM", "babyblogRU", "chaos.social",
    "couchsurfing", "d3RU", "dailykos", "datingRU", "dcinside", "devRant",
    "drive2", "eGPU", "eintracht", "exophase", "fixya", "fl",
    "forum_guns", "freecodecamp", "furaffinity", "geocaching", "habr", "hackster",
    "hunting", "igromania", "imood", "interpals", "irecommend", "jbzd.com.pl",
    "jeuxvideo", "kaskus", "kofi", "kwork", "last.fm", "leasehackr",
    "livelib", "mastodon.cloud", "mastodon.social", "mastodon.xyz", "mercadolivre", "minds",
    "moikrug", "mstdn.io", "mstdn.social", "n8n Community", "nairaland.com", "namuwiki",
    "nnRU", "note", "npm", "omg.lol", "opennet", "osu!",
    "phpRU", "pikabu", "pixelfed.social", "pr0gramm", "prog.hu", "programming.dev",
    "satsisRU", "sessionize", "social.tchncs.de", "spletnik", "svidbook", "threads",
    "tistory", "toster", "tumblr", "uid", "write.as", "xHamster",
    "znanylekarz.pl",
}
