SHERLOCK_SITES = {
    "1337x", "2Dimensions", "7Cups", "9GAG", "APClips", "About.me",
    "Academia.edu", "AdmireMe.Vip", "Airbit", "Airliners", "All Things Worn",
    "AllMyLinks", "AniWorld", "Anilist", "Apple Developer", "Apple Discussions",
    "Archive of Our Own", "Archive.org", "ArtStation", "Asciinema", "Ask Fedora",
    "Atcoder", "Audiojungle", "Autofrage", "Avizo", "BOOTH", "Bandcamp",
    "Bazar.cz", "Behance", "Bezuzyteczna", "BiggerPockets", "BioHacking",
    "BitBucket", "Bitwarden Forum", "Blipfoto", "Blitz Tactics", "Blogger",
    "Bluesky", "BoardGameGeek", "BongaCams", "Bookcrossing", "BraveCommunity",
    "BugCrowd", "BuyMeACoffee", "BuzzFeed", "CGTrader", "CNET", "CSSBattle",
    "CTAN", "Caddy Community", "Car Talk Community", "Carbonmade",
    "Career.habr", "CashApp", "Championat", "Chaos", "Chatujme.cz",
    "ChaturBate", "Chess", "Choice Community", "Clapper",
    "CloudflareCommunity", "Clozemaster", "Clubhouse", "Code Snippet Wiki",
    "Codeberg", "Codecademy", "Codechef", "Codeforces", "Codepen",
    "Coders Rank", "Coderwall", "Codewars", "Coinvote", "ColourLovers",
    "Contently", "Coroflot", "Cracked", "Crevado", "Crowdin",
    "Cryptomator Forum", "Cults3D", "CyberDefenders", "DEV Community", "DMOJ",
    "DailyMotion", "Dealabs", "DeviantART", "DigitalSpy", "Discogs", "Discord",
    "Discuss.Elastic.co", "Disqus", "Docker Hub", "Dribbble", "Duolingo",
    "Eintracht Frankfurt Forum", "Empretienda AR", "Envato Forum", "Erome",
    "Exposure", "EyeEm", "F3.cool", "Fameswap", "Fandom", "Fanpop",
    "Finanzfrage", "Flickr", "Flightradar24", "Flipboard", "Football",
    "FortniteTracker", "Forum Ophilia", "Fosstodon", "Framapiaf",
    "Freelance.habr", "Freelancer", "Freesound", "GNOME VCS", "GaiaOnline",
    "Gamespot", "GeeksforGeeks", "Genius (Artists)", "Genius (Users)",
    "Gesundheitsfrage", "GetMyUni", "Giant Bomb", "Giphy", "GitBook", "GitHub",
    "GitLab", "Gitea", "Gitee", "GoodReads", "Google Play", "Gradle",
    "Grailed", "Gravatar", "Gumroad", "Gutefrage", "HackTheBox", "Hackaday",
    "HackenProof (Hackers)", "HackerEarth", "HackerNews", "HackerOne",
    "HackerRank", "Harvard Scholar", "Hashnode", "Heavy-R", "Holopin", "Houzz",
    "HubPages", "Hubski", "HudsonRock", "Hugging Face", "IFTTT", "IRC-Galleria",
    "Icons8 Community", "Image Fap", "ImgUp.cz", "Imgur", "Instagram",
    "Instructables", "Intigriti", "Ionic Forum", "Issuu", "Itch.io", "Itemfix",
    "Jellyfin Weblate", "Jimdo", "Joplin Forum", "Kaggle", "Keybase", "Kick",
    "Kik", "Kongregate", "LOR", "Launchpad", "LeetCode", "LessWrong",
    "Letterboxd", "LibraryThing", "Lichess", "LinkedIn", "Linktree",
    "LinuxFR.org", "Listed", "LiveJournal", "Lobsters", "LottieFiles",
    "LushStories", "MMORPG Forum", "Mamot", "Medium", "Memrise", "Minecraft",
    "MixCloud", "Monkeytype", "Motherless", "Motorradfrage", "MyAnimeList",
    "MyMiniFactory", "Mydramalist", "Myspace", "NICommunityForum",
    "NationStates Nation", "NationStates Region", "Naver", "Needrom",
    "Newgrounds", "Nextcloud Forum", "Nightbot", "Ninja Kiwi", "NintendoLife",
    "NitroType", "NotABug.org", "Nyaa.si", "Open Collective", "OpenStreetMap",
    "Opensource", "OurDJTalk", "Outgress", "PCGamer", "PSNProfiles.com",
    "Packagist", "Pastebin", "Patreon", "PentesterLab", "PepperIT",
    "Periscope", "Pinkbike", "Platzi", "PlayStore", "Playstrategy", "Plurk",
    "PocketStars", "Pokemon Showdown", "Polarsteps", "Polygon", "Polymart",
    "Pornhub", "ProductHunt", "PromoDJ", "PyPi", "Pychess", "Rajce.net",
    "Rarible", "Rate Your Music", "Rclone Forum", "RedTube", "Redbubble",
    "Reddit", "Reisefrage", "Replit.com", "ResearchGate", "ReverbNation",
    "Roblox", "RocketTube", "RoyalCams", "RubyGems", "Rumble", "RuneScape",
    "SWAPD", "Sbazar.cz", "Scratch", "Scribd", "ShitpostBot5000", "Signal",
    "Sketchfab", "Slack", "Slant", "Slashdot", "SlideShare", "Slides",
    "SmugMug", "Smule", "Snapchat", "SoundCloud", "SourceForge",
    "SoylentNews", "SpeakerDeck", "Speedrun.com", "Spells8", "Splice",
    "Splits.io", "Sporcle", "Sportlerfrage", "SportsRU", "Spotify",
    "Star Citizen", "Steam Community (Group)", "Steam Community (User)",
    "Strava", "SublimeForum", "TETR.IO", "TRAKTRAIN", "Telegram",
    "Tellonym.me", "Tenor", "ThemeForest", "Tiendanube", "TnAFlix",
    "Topcoder", "TradingView", "Trakt", "TrashboxRU", "Trawelling", "Trello",
    "TryHackMe", "Tuna", "Tweakers", "Twitter", "Typeracer",
    "Ultimate-Guitar", "Unsplash", "Untappd", "VK", "VLR", "VSCO", "Velog",
    "Velomania", "Venmo", "Vero", "Vimeo", "VirusTotal", "WICG Forum",
    "Warrior Forum", "Wattpad", "WebNode", "Weblate", "Weebly", "Wikidot",
    "Wikipedia", "Windy", "Wix", "WolframalphaForum", "WordPress",
    "WordPressOrg", "Wordnik", "Wykop", "Xbox Gamertag", "Xvideos",
    "YandexMusic", "YouNow", "YouPic", "YouPorn", "YouTube", "akniga",
    "authorSTREAM", "babyblogRU", "chaos.social", "couchsurfing", "d3RU",
    "dailykos", "datingRU", "devRant", "drive2", "eGPU", "eintracht",
    "exophase", "fixya", "fl", "forum_guns", "freecodecamp", "furaffinity",
    "geocaching", "habr", "hackster", "hunting", "igromania", "interpals",
    "irecommend", "jbzd.com.pl", "jeuxvideo", "kaskus", "kofi", "kwork",
    "last.fm", "leasehackr", "livelib", "mastodon.cloud", "mastodon.social",
    "mastodon.xyz", "mercadolivre", "minds", "moikrug", "mstdn.io",
    "nairaland.com", "nnRU", "note", "npm", "omg.lol", "opennet", "osu!",
    "phpRU", "pikabu", "pixelfed.social", "pr0gramm", "prog.hu",
    "programming.dev", "satsisRU", "sessionize", "social.tchncs.de",
    "spletnik", "svidbook", "threads", "toster", "tumblr", "uid", "write.as",
    "xHamster", "znanylekarz.pl",
}
